package solutions

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

// Problem002 - Even Fibonacci numbers
func (p *Problem) Problem002() int {
	const limit = 4000000
	retval := 2 // since 2 will never be evaluted to be added
	var c int
	a := 1
	b := 2
	for retval < limit {

		c = a + b
		if c%2 == 0 {
			retval += c
		}

		a = b
		b = c

	}

	return retval
}
